### ISSUE TITLE
Make all dependencies available on Maven Central

### ISSUE THREAD

**Issue by lutzh** [outworkers/phantom#544]
Maven Central is supposed to be self-contained, i.e. all the dependencies of artifacts published there should also be available on Maven Central, at least that's a guideline. See https://maven.apache.org/guides/mini/guide-central-repository-upload.html

> we do strongly encourage making sure all your dependencies are included in Central

Not following this might actually hurt Phantom adoption, see https://twitter.com/_JamesWard/status/766361703424458752

Would it be possible that all Phantom dependencies also be published on Central? It seem currently at least `Resolver.bintrayRepo("websudos", "oss-releases")` is necessary as an additional repository.

**Comment by alexflav23** [comment]
Hi @lutzh,

Thank you for reporting this to us, I've added is as a high priority item for next week, so all future versions of phantom will exclude the need to have a Bintray resolver.

Regards.

**Comment by alexflav23** [comment]
Hi @lutzh,

Fixed as of phantom 1.30.x, should come live by Monday on Maven Central, external resolvers no longer required. Many many thanks for the issue report and for pointing things our way, it's much appreciated.

I owe you a few drinks in London anyway, I'll pop down to CodeNode for your next gig to say hi.

Regards.

**Comment by macalinao** [comment]
This is still not fixed, unless I'm doing something wrong.

http://repo1.maven.org/maven2/com/websudos/phantom-dsl_2.11/

**Comment by alexflav23** [comment]
Hi @macalinao,

1.30.x is going to fix this, we've automated all deployment,  waiting on one PR to merge.

This is pretty much outside of phantom now, it's the diesel-engine that is waiting for a fixed PR. I understand your reluctance to not go 100% Maven Central, but what I would suggest is that you could start using phantom straight away.

As soon diesel engine hits maven central, SBT will automatically prefer that. As the most widely adopted Cassandra tool, the odds of us pulling a version or any user disruptive behaviour are 0. 

Regards.

**Comment by maxthomas** [comment]
Any updates on this? 

Bintray is currently serving out `403 Forbidden` across 3 different proxies of mine for [this URL](https://dl.bintray.com/websudos/oss-releases/com/outworkers/diesel-engine_2.10/0.4.1/diesel-engine_2.10-0.4.1.pom). This is a complete blocker to using your library.

**Comment by alexflav23** [comment]
HI @maxthomas,

We are in the process of moving resolvers to `Resolver.bintrayRepo("outworkers", "oss-releases")` but the current repo should be stable. Everything is going on Maven Central by the end of the week, there has been a lot of progress made for Phantom 2.0.0 to be fully on Maven Central, but some of the publishing hasn't been done retroactively, sounds like that might be a great idea.

Thank you for your feedback, we will fix this by publishing older versions of dependencies to Maven Central.

Regards,
Flavian

**Comment by maxthomas** [comment]
great, thanks for the quick update!

**Comment by alexflav23** [comment]
Hi @maxthomas @macalinao @jamesward This has been fixed as of 1.29.6, all the complex resolutions internally have been removed, and everything is on Maven Central. Furthermore, all dependencies now use an Apache License and as of 2.0.0 so does phantom.

We have physically removed the custom bintray resolver from inside the phantom build.

**Comment by macalinao** [comment]
woot woot!
